#!/usr/bin/env bash
# tools/amalgamate.sh — Generate single-header SDK: include/linux/socketley.h
# Usage: bash tools/amalgamate.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/include/linux/socketley.h"

SRC="$REPO_ROOT/socketley"

# ─── File lists (dependency order) ───

HEADERS=(
    # Tier 1: no internal deps
    "$SRC/cli/command_hashing.h"
    "$SRC/shared/runtime_definitions.h"
    "$SRC/cli/runtime_type_parser.h"
    "$SRC/shared/event_loop_definitions.h"
    "$SRC/shared/id_generator.h"
    "$SRC/shared/scoped_fd.h"
    "$SRC/shared/logging.h"
    "$SRC/shared/time_format.h"
    # Tier 2
    "$SRC/shared/paths.h"
    "$SRC/shared/name_resolver.h"
    # Tier 3
    "$SRC/shared/ws_protocol.h"
    "$SRC/shared/tls_context.h"
    "$SRC/runtime/cache/resp_parser.h"
    # Tier 4
    "$SRC/runtime/cache/cache_store.h"
    # Tier 5
    "$SRC/shared/event_loop.h"
    # Tier 6
    "$SRC/shared/daemon_client.h"
    "$SRC/shared/lua_context.h"
    # Tier 7
    "$SRC/shared/runtime_instance.h"
    # Tier 8
    "$SRC/shared/state_persistence.h"
    "$SRC/shared/cluster_discovery.h"
    "$SRC/shared/runtime_manager.h"
    # Tier 9
    "$SRC/shared/runtime_factory.h"
    # Tier 10
    "$SRC/runtime/server/server_instance.h"
    "$SRC/runtime/client/client_instance.h"
    "$SRC/runtime/proxy/proxy_instance.h"
    "$SRC/runtime/cache/cache_instance.h"
)

SOURCES=(
    "$SRC/shared/paths.cpp"
    "$SRC/shared/tls_context.cpp"
    "$SRC/shared/event_loop.cpp"
    "$SRC/shared/daemon_client.cpp"
    "$SRC/shared/lua_context.cpp"
    "$SRC/shared/runtime_instance.cpp"
    "$SRC/runtime/cache/cache_store.cpp"
    "$SRC/shared/state_persistence.cpp"
    "$SRC/shared/cluster_discovery.cpp"
    "$SRC/shared/runtime_manager.cpp"
    "$SRC/shared/runtime_factory.cpp"
    "$SRC/runtime/server/server_instance.cpp"
    "$SRC/runtime/client/client_instance.cpp"
    "$SRC/runtime/proxy/proxy_instance.cpp"
    "$SRC/runtime/cache/cache_instance.cpp"
)

# ─── Collect and deduplicate system includes ───

declare -A SEEN_INCLUDES
SYSTEM_INCLUDES=()
LUA_INCLUDES=()

collect_includes() {
    local file="$1"
    while IFS= read -r line; do
        # Match #include <...>
        if [[ "$line" =~ ^[[:space:]]*\#[[:space:]]*include[[:space:]]*\<([^\>]+)\> ]]; then
            local inc="${BASH_REMATCH[1]}"
            if [[ -z "${SEEN_INCLUDES[$inc]+x}" ]]; then
                SEEN_INCLUDES["$inc"]=1
                if [[ "$inc" == sol/* ]]; then
                    LUA_INCLUDES+=("$inc")
                else
                    SYSTEM_INCLUDES+=("$inc")
                fi
            fi
        fi
    done < "$file"
}

for f in "${HEADERS[@]}" "${SOURCES[@]}"; do
    collect_includes "$f"
done

# Sort system includes
IFS=$'\n' SYSTEM_INCLUDES=($(sort <<<"${SYSTEM_INCLUDES[*]}")); unset IFS

# ─── Helper: strip local includes, #pragma once, namespace fs alias ───

strip_file() {
    local file="$1"
    while IFS= read -r line; do
        # Skip #pragma once
        [[ "$line" =~ ^[[:space:]]*\#[[:space:]]*pragma[[:space:]]+once ]] && continue
        # Skip #include "..." (local includes)
        [[ "$line" =~ ^[[:space:]]*\#[[:space:]]*include[[:space:]]*\" ]] && continue
        # Skip #include <...> (system includes — already emitted)
        [[ "$line" =~ ^[[:space:]]*\#[[:space:]]*include[[:space:]]*\< ]] && continue
        # Skip namespace fs = std::filesystem;
        [[ "$line" =~ ^[[:space:]]*namespace[[:space:]]+fs[[:space:]]*=[[:space:]]*std::filesystem ]] && continue
        printf '%s\n' "$line"
    done < "$file"
}

basename_label() {
    local f="$1"
    echo "${f#$REPO_ROOT/}"
}

# ─── Generate output ───

{
    # Prologue
    cat <<'PROLOGUE'
// ╔═══════════════════════════════════════════════════════════════════╗
// ║  socketley.h — Single-header SDK (stb-style)                    ║
// ║  Auto-generated by tools/amalgamate.sh — DO NOT EDIT BY HAND    ║
// ║                                                                  ║
// ║  Usage:                                                          ║
// ║    #define SOCKETLEY_IMPLEMENTATION   // in exactly ONE .cpp     ║
// ║    #include "socketley.h"                                        ║
// ║                                                                  ║
// ║  Optional defines (before #include):                             ║
// ║    #define SOCKETLEY_NO_LUA    — disable Lua/sol2 dependency     ║
// ║    #define SOCKETLEY_NO_HTTPS  — disable HTTP client in Lua      ║
// ║                                                                  ║
// ║  Link: -luring -lssl -lcrypto [-lluajit-5.1]                    ║
// ╚═══════════════════════════════════════════════════════════════════╝
#ifndef SOCKETLEY_H
#define SOCKETLEY_H

#ifndef __linux__
#  error "Socketley requires Linux (io_uring, kernel 5.11+)"
#endif

PROLOGUE

    # System includes
    echo "// ── System includes ──"
    echo ""
    for inc in "${SYSTEM_INCLUDES[@]}"; do
        echo "#include <${inc}>"
    done

    # Lua includes (guarded)
    echo ""
    echo "#ifndef SOCKETLEY_NO_LUA"
    for inc in "${LUA_INCLUDES[@]}"; do
        echo "#include <${inc}>"
    done
    echo "#endif // SOCKETLEY_NO_LUA"
    echo ""

    # ─── Declarations (headers) ───

    echo "// ════════════════════════════════════════════════════════════════════"
    echo "//  DECLARATIONS"
    echo "// ════════════════════════════════════════════════════════════════════"
    echo ""

    for hdr in "${HEADERS[@]}"; do
        label="$(basename_label "$hdr")"
        echo "// ── ${label} ──"
        echo ""
        strip_file "$hdr"
        echo ""
    done

    # ─── Implementation ───

    echo "#ifdef SOCKETLEY_IMPLEMENTATION"
    echo ""
    echo "// ════════════════════════════════════════════════════════════════════"
    echo "//  IMPLEMENTATION"
    echo "// ════════════════════════════════════════════════════════════════════"
    echo ""
    echo "namespace fs = std::filesystem;"
    echo ""

    for src in "${SOURCES[@]}"; do
        label="$(basename_label "$src")"
        echo "// ── ${label} ──"
        echo ""
        strip_file "$src"
        echo ""
    done

    echo "#endif // SOCKETLEY_IMPLEMENTATION"
    echo ""
    echo "#endif // SOCKETLEY_H"

} > "$OUT"

LINES=$(wc -l < "$OUT")
echo "Generated $OUT ($LINES lines)"
